global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'rohansen856@gmail.com'
  smtp_auth_username: 'rohansen856@gmail.com'
  smtp_auth_password: 'bnoc ooxb tvpl ufzh'
  smtp_auth_password: '{{ getenv "SMTP_PASSWORD" }}'

route:
  group_by: ['sysplex', 'severity']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 12h
  receiver: 'mainframe-ops'
  routes:
    - match:
        severity: critical
      receiver: 'mainframe-critical'

receivers:
  - name: 'mainframe-ops'
    email_configs:
      - to: 'rohansen856@gmail.com'

  - name: 'mainframe-critical'
    email_configs:
      - to: 'rohansen856@gmail.com'