apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmf-simulator
  namespace: rmf-monitoring
  labels:
    app: rmf-simulator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rmf-simulator
  template:
    metadata:
      labels:
        app: rmf-simulator
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: rmf-simulator
      containers:
      - name: rmf-simulator
        image: rmf-simulator:latest
        ports:
        - containerPort: 8000
          name: http
        envFrom:
        - configMapRef:
            name: rmf-simulator-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /startup
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 30
        volumeMounts:
        - name: prometheus-tmp
          mountPath: /tmp/prometheus_multiproc_dir
      volumes:
      - name: prometheus-tmp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: rmf-simulator
  namespace: rmf-monitoring
  labels:
    app: rmf-simulator
spec:
  selector:
    app: rmf-simulator
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rmf-simulator-hpa
  namespace: rmf-monitoring
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rmf-simulator
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80