global:
  smtp_smarthost: 'smtp.company.com:587'
  smtp_from: 'alerts@company.com'

route:
  group_by: ['sysplex', 'severity']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 12h
  receiver: 'mainframe-ops'
  routes:
    - match:
        severity: critical
      receiver: 'mainframe-critical'

receivers:
  - name: 'mainframe-ops'
    email_configs:
      - to: 'mainframe-ops@company.com'
        subject: 'Mainframe Alert: {{.GroupLabels.sysplex}}'
        body: |
          {{range .Alerts}}
          Alert: {{.Annotations.summary}}
          System: {{.Labels.sysplex}}
          LPAR: {{.Labels.lpar}}
          {{end}}

  - name: 'mainframe-critical'
    email_configs:
      - to: 'mainframe-critical@company.com'
        subject: 'CRITICAL: Mainframe Alert: {{.GroupLabels.sysplex}}'
        body: |
          {{range .Alerts}}
          CRITICAL ALERT: {{.Annotations.summary}}
          System: {{.Labels.sysplex}}
          LPAR: {{.Labels.lpar}}
          Description: {{.Annotations.description}}
          {{end}}